---
name: build-image
on:
  push:
    # branches:
      # - release
  schedule:
    - cron: "20 22 * * 0"
  workflow_dispatch:
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # - name: Checkout Push to Registry action
        # uses: actions/checkout@v4

      - name: Get date for image tag
        id: date
        run: echo "DATE=$(date +'%y%m%d')" >> $GITHUB_ENV

      # - name: Build image
      #   id: build_image
      #   uses: redhat-actions/buildah-build@v2
      #   with:
      #     containerfiles: |
      #       ./Containerfile
      #     image: gneiss
      #     tags: 39 39.${{ env.DATE }}
      #     build-args: |
      #       FEDORA_MAJOR_VERSION=39
      #       NVIDIA_MAJOR_VERSION=535
      #     oci: false

      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: gneiss
          tags: 39
          base-image: busybox:latest
          entrypoint: |
            bash
            -c
            echo 'hello world'
          oci: false

      - name: Push image to registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
