---
name: build-image
on:
  push:
  schedule:
    - cron: 0 18 * * 5
  workflow_dispatch:
env:
  FEDORA_MAJOR_VERSION: 41
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get date for image tag
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Update build counter
        run: |
          set -x

          if [ "$LAST_RUN_DATE" == "`date +'%Y%m%d'`" ]; then
            echo "BUILD_COUNT=$((BUILD_COUNT + 1))" >> $GITHUB_ENV
          else
            echo "BUILD_COUNT=0" >> $GITHUB_ENV
          fi

          echo "LAST_RUN_DATE=`date +'%Y%m%d'`" >> $GITHUB_ENV
        env:
          BUILD_COUNT: ${{ vars.BUILD_COUNT }}
          LAST_RUN_DATE: ${{ vars.LAST_RUN_DATE }}

      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: gneiss
          tags: ${{ env.FEDORA_MAJOR_VERSION }} ${{ env.FEDORA_MAJOR_VERSION }}.${{ env.DATE }}.${{ env.BUILD_COUNT }}
          build-args: |
            FEDORA_MAJOR_VERSION=${{ env.FEDORA_MAJOR_VERSION }}
          labels: |
            org.opencontainers.image.title=gneiss
            org.opencontainers.image.version=${{ env.FEDORA_MAJOR_VERSION }}.${{ env.DATE }}.${{ env.BUILD_COUNT }}

      - name: Push image to registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Update build count repository variable
        uses: action-pack/set-variable@v1
        with:
          name: "BUILD_COUNT"
          value: ${{ env.BUILD_COUNT }}
          token: ${{ secrets.SET_VARIABLE_TOKEN }}

      - name: Update last run date repository variable
        uses: action-pack/set-variable@v1
        with:
          name: "LAST_RUN_DATE"
          value: ${{ env.LAST_RUN_DATE }}
          token: ${{ secrets.SET_VARIABLE_TOKEN }}
